#!/usr/bin/env bash
# for run script in the background use the command "nohup bash script.sh &" or use systemd
export URL=http://www.example.com
export token=<your_telegram_bot_token>
export sendMessageURL=https://api.telegram.org/bot$token/sendMessage
export chat_id=<your_telegram_chat_id>

i=1
while((i == 1))
do
response=$(curl -I $URL -o /dev/null -w '%{http_code}\n' -s)
if (($response == 200))
  then
  date >>log.txt
  echo ok. service status: $response >>log.txt
  sleep 300
else
  date >>log.txt
  echo error. service status: $response >>log.txt
  sleep 90
  recheck=$(curl -I $URL -o /dev/null -w '%{http_code}\n' -s)
  if (($recheck == 200))
    then
    date >>log.txt
    echo recheck ok, status $recheck >>log.txt
  else
    date >>log.txt
    echo error. service status after recheck: $recheck >>log.txt
    curl -s -X POST $sendMessageURL -F chat_id=$chat_id -F text="service is not available. Recheck status: $recheck"
    sleep 300
  fi
fi
done
